rest-service v0.2.0;
DonVietnam/mentoring pull request #3
Opened 2022-01-11 17:55 UTC by cbrgpl

Точка входа для изучения структуры кода `service/service.js`

2022-01-11 17:57 UTC, cbrgpl commented
Протупил с тем, что без примеров использования сложно понять что почему и зачем.

2022-01-11 18:00 UTC, cbrgpl commented
Вот пример использования Api-классов

```js
const ApiModule = require( './service/apiModule' );
const Fetcher = require( './service/fetcher' );

const API_URL = '12/';

const user1 = {
  name: 'Dmitry',
  family: true,
  age: 20,
};

const apiScheme = {
  user: {
    create: {
      path: API_URL + 'create-user/',
      fetchParams: {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Credentials: 'include',
        },
      },
      body: null,
    },
    get: {
      path: API_URL + 'get-users',
      fetchParams: {
        method: 'GET',
        headers: {
          'Accept': 'application/json',
          Credentals: 'include'
        }
      },
      queryParams: null,
    },
    delete: {
      path: API_URL + 'delete-user/{{id}}/',
      fetchParams: {
        method: 'DELETE',
        headers: {
          Credentials: 'include'
        },
      },
      id: null,
      queryParams: null,
    }
  }
};

const apiModule = new ApiModule( apiScheme.user );
const regObj = {};

regObj.create  = apiModule.getRequestParams( {
  endpointName: 'create',
} );

regObj.get = apiModule.getRequestParams( {
  endpointName: 'get',
  queryParams: {
    quantity: 10
  },
} );

regObj.detele = apiModule.getRequestParams( {
  endpointName: 'delete',
  queryParams: {
    hard: true
  },
  id: '1001'
} );

```

Схема АПИ - это шаблоны, которые используются для последующей генерации параметров к запросу. В случае, если в схеме значение поля шаблона указано null, то поле предполагается динамическим(т.е. должно быть сформированно непосредственно перед запросом, это обусловлено не константностью данных для разных запросов).
Я решил принудить пользователей к тому, чтобы они заранее объвляли в схеме, будет ли использовать какой-либо параметр, посредством указания значения `null`. Если значения `null` не будет, то переданное конкретное значение будет игнорироваться

2022-01-11 18:04 UTC, cbrgpl commented
```js
const ResponseProcessor = require( './service/responseProcessor' );

  const mimeParsers = {
    'application/json': ( response ) => response.json()
  };

  const response = await fetch( 'https://jsonplaceholder.typicode.com/todos/1' );
  const respProc = new ResponseProcessor( mimeParsers );
  const a = respProc.processResponse( response );

  ```
  
  Создает парсер респонсов, который производит проверку на неправильные статусы ответа(в случае неправильного статуса выкидывает `StatusError`).  Применяет заведомо установленный для конкретного типа данных парсер. Плюсом такого подхода является то, что можно использовать один и тот же респонс для разных сервисов, как правило на проекте едины правила обработки данных и статусов. Но так же можно создать парочку экземпляров, для обработки каких-то исключительных случаев

2022-01-11 18:04 UTC, cbrgpl commented
Думаю дальше все будет понятно

2022-01-13 05:53 UTC, DonVietnam requested changes
Посмотри на предложении по изменению схем, потом уже дальше будем смотреть, что получится.
Потому что вот эти схемы с непостоянными полями и null, это не схемы - это уже данные просто без значений, схемы должны описывать типы, причём без привязки к методу запроса, метод запроса вообще не должен волновать и интересовать программиста на клиенте, пишущего компонент.

2022-01-13 05:53 UTC, DonVietnam commented on Practice/cbrgpl/error/statusError.js
> +    this.message = `Got invalid status;\nstatus - ${ status },\nurl - ${ url }`;
Ты переопределил стандартное поле ошибки message. Либо дополняй его, чтобы не терять изначальную информацию, либо определяй другое поле для себя.

2022-01-13 05:53 UTC, DonVietnam commented on Practice/cbrgpl/error/statusError.js
> +    this.message = `Got invalid status;\nstatus - ${ status },\nurl - ${ url }`;
Invalid - не совсем верное название, так как статус будет в любом случае правильным, другое дело, что это может быть статус с ошибкой то есть -  error status.

2022-01-13 05:53 UTC, DonVietnam commented on Practice/cbrgpl/helper/isFunction.js
> +module.exports.isFunction = ( val ) => typeof val === 'function';
Субъективно, но смысл заменять одну строчку кода на другую я не вижу. В этом случае наоборот постоянно будет ещё и вызов функции происходить во всех местах, где ты будешь на функцию проверку делать.
Можно, конечно, сказать, что это на будущее, мало ли что-то измениться в стандарте, но шанс этого крайне мал.
В проверке на объект смысл есть, потому что операторов там много и что-то можно забыть.

2022-01-13 05:53 UTC, DonVietnam commented on Practice/cbrgpl/helper/lookbehindAnalog.js
> +};
Почитал вот тут https://javascript.info/regexp-lookahead-lookbehind про lookbehind, там регулярка немного другая, то что ты тут привёл точно делает ту же задачу? Если да, то вопросов нет. Ну и слово analog, я бы убрал.

2022-01-13 05:53 UTC, DonVietnam commented on Practice/cbrgpl/error/endpointError.js
> +module.exports = class EndpointError extends Error {
Ты экспортируешь функции, как поля объектов, что позволяет пользоваться деструктуризацией, а классы почему-то напрямую кладёшь в переменную exports, приди к единообразию.

2022-01-13 05:53 UTC, DonVietnam commented on Practice/cbrgpl/service/apiEndpoint.js
> +};
Сделай свои схемы немного по-другому.
1. У каждого endpoint должны быть его мета-данные. Метод "POST" или "GET", путь "/some/path", schema - схема с параметрами, которые нужны для endpoint. 
2. Параметры, которые будут поступать в маршрут, можешь проверять с помощью этой самой схемы. Пишешь её в формате JSON Schema и проверяешь фактические параметры с помощью библиотеки ajv. Это достаточно гибкая схема и не заставить людей парится насчёт того, какой тип запроса и прочее, они просто вызывают нужный метод и передают ему аргументы.
3. Дальше после того, как клиент вызвал метод и передал нужные аргументы, ты их проверяешь с помощью схемы, которая ничего не знает о типе запроса, а потом уже смотришь на тип запроса и в зависимости от него складываешь параметры в нужный формат. И отправляешь.

Соблюдая такую схему, мы сможем интегрировать бэкенд и фронтенд друг с другом, я смогу просто отправлять тебе нужные схемы и маршруты, а ты автоматически сможешь по ним генерировать нужный функции для api.

Вот пример того, как у меня описаны параметры для запросов:

```
list: { //имя endpoint, дальше формат JSONSchema.
    type: 'object',
    required: [],
    properties: {
      filters: {
        type: 'object',
        required: [],
        properties: {
          workerId: {
            type: 'string'
          },
          statusId: {
            type: 'string'
          },
          purposeId: {
            type: 'string'
          },
        },
        additionalProperties: false
      },
      pages: {
        type: 'object',
        required: [ 'itemsNumber', 'page' ],
        properties: {
          itemsNumber: {
            type: 'string',
          },
          page: {
            type: 'string'
          }
        },
        additionalProperties: false
      },
    },
    additionalProperties: false
  },
```
Вот пример схемы с мета данными об endpoint:
```
{
      method: 'POST',
      path: '/ticket/create',
      secure: false,
      schema: component.schemes.create,
      handler: 'create',
      roles: []
    },
```
Поля с авторизацией можно игнорировать, а можно и проверять, тут не настаиваю.

2022-01-16 12:42 UTC, cbrgpl commented on Practice/cbrgpl/helper/isFunction.js
> +module.exports.isFunction = ( val ) => typeof val === 'function';
Оставлю, во-первых менять уже не охото везде, я ее часто использую, во-вторых так проще код читать, не выглядит так нагроможденно как само условие

2022-01-16 12:53 UTC, cbrgpl commented
@DonVietnam v0.3.0

2022-01-18 09:42 UTC, DonVietnam requested changes
Уже вырисовывается что-то, облегчающее жизнь. Но всё же выдели времени пару часиков и поучись писать модульные тесы с помощью того же jest. Потому что это тестами назвать проблематично.

2022-01-18 09:42 UTC, DonVietnam commented on Practice/cbrgpl/service/apiEndpoint.js
> +        url: path,
Path - это path, url - это url.

2022-01-18 09:42 UTC, DonVietnam commented on Practice/cbrgpl/service/apiEndpoint.js
> +  bindDataToRequest( path, data ) {
Не похоже чтобы тут какая-то data к какому-то запросу привязывалась.

2022-01-18 09:42 UTC, DonVietnam commented on Practice/cbrgpl/service/apiEndpoint.js
> +      body: NO_CONTENT_TYPE,
Тело запроса присвоить значение 'NO_CONTENT_TYPE', это как понимать? Если тело пустое, то пусть прилетает пустое, если запрос не подразумевает тело запроса, то почему два принципиально разных запроса тут вместе обрабатываются?

2022-01-18 09:42 UTC, DonVietnam commented on Practice/cbrgpl/service/apiEndpoint.js
> +    if( this.endpointMetadata.useBody ) {
Для этих целей служит method, потому что именно от него зависит, будет body или нет.

2022-01-18 09:42 UTC, DonVietnam commented on Practice/cbrgpl/service/mimeTypeParser.js
> +    const expectedMimeType = Object.keys( this.mimeParserPairs );
Тут вроде коллекция MIME типов будет, а не один.

2022-01-18 09:42 UTC, DonVietnam commented on Practice/cbrgpl/service/mimeTypeParser.js
> +  defineMimeType( httpResponse ) {
Если я правильно понял, эта функция либо получает, либо ищет mimeType  в заголовке.

2022-01-18 09:42 UTC, DonVietnam commented on Practice/cbrgpl/service/responseProcessor.js
> +  constructor( mimeParserPairs, invalidStatuses = [] ) {
Вот как только ты вынес определение mimeParserPairs из этого класса, реализация и внутренности твоего класса ResponseProcessor "потекли" наружу. Скорее всего в обязанности этого класса просто не входит создание объекта mimeTypeParser, он может его получать, но возлагать на него ответственность за создание не стоит.

2022-01-18 09:42 UTC, DonVietnam commented on Practice/cbrgpl/service/service.js
> +    this.responseProcessor = responseProcessor === null ? new ResponseProcessor( mimeParserPairs, invalidStatuses ) : responseProcessor;
Вот это вот прокидывание параметров сквозь классы посредники нужно убрать. Пусть ответственность за создание responseProcessor полностью лежит за пределами этого класса.

2022-01-18 09:42 UTC, DonVietnam commented on Practice/cbrgpl/service/service.js
> +      this[ handlerName ] = async ( { data, id } ) => {
Единственное я бы всё-таки разделил на два аргумента ( data, id ), чтобы можно было писать service.method( { prop1, prop2 } ), а не оборачивать всё это в ещё один объект со свойством data.

2022-01-18 09:42 UTC, DonVietnam commented on Practice/cbrgpl/service/serviceFactory.js
> +  constructor( { ServiceClass = Service, mimeParserPairs } ) {
Это что-то похожее на фабричный метод, но реализовано как-то странно и непонятно. Также не ясно зачем это тут нужно, у тебя, вроде, один класс Service. Идея сделать фабрику неплохая, но она нужна скорее как абстракция для сложного создания сервисов, а не для выпуска разных сервисов с помощью одного интерфейса. Фабрика нужна, но не нужно пихать туда аргументом класс.

2022-01-18 10:40 UTC, cbrgpl commented on Practice/cbrgpl/helper/endpointMetadataScheme.js
> +};
@DonVietnam 
Папка для вспомогательных сущностей любого вида(функция, схема, класс), если будет больше схем, то можно уже будет создать отдельную директроию для схем, но их больше 3х не будет.

А на счет AJV - если где-то еще будет необходима валидация с помощью ajv, чтобы не тратить ресурсы на создание копии решил так сделать

2022-01-18 11:39 UTC, cbrgpl commented on Practice/cbrgpl/service/apiEndpoint.js
> +        url: path,
В целом path && url это смежные понятия в данном контексте, я решил разделить на 2 слова по таким значениям:

path - неподготовленный адрес энпоинта
url - сформированный адрес эндпоинта

В контексте этой функции она принимает именно path, но возвращать она должна уже url

2022-01-18 12:27 UTC, cbrgpl commented on Practice/cbrgpl/service/responseProcessor.js
> +  constructor( mimeParserPairs, invalidStatuses = [] ) {
@DonVietnam  А как понять когда уместно возлагать на какой-то класс создание его вспомогательного класса, а когда нет? Я тут размышлял по принципу `"Чем меньше нужно делать для использования класса, тем лучше"`

2022-01-18 12:32 UTC, cbrgpl commented on Practice/cbrgpl/service/serviceFactory.js
> +  constructor( { ServiceClass = Service, mimeParserPairs } ) {
@DonVietnam Я подумал, что для специфики какого-то проекта возможно понадобится делать обертку над сервисом, причем каждый используемый на проекте сервис будет такого "оберточного" типа. И чтобы не писать свою собственную фабрику по производству сервисов я решил сделать возможность переопределения класса сервиса, это мелочь, которая никак не скажется на работе, но может решить некоторые проблемы и сэкономить время

Насчет фабричного метода посмотрю как более правильно реализовать паттерн

2022-01-18 12:35 UTC, cbrgpl commented on Practice/cbrgpl/service/mimeTypeParser.js
> +  defineMimeType( httpResponse ) {
Нет, только ищет в заголове

2022-01-18 12:38 UTC, cbrgpl commented
@DonVietnam насчет тестов я не буду тебе кидать тесты на проверку, я на проверку кидаю именно содержимое функционала, поэтому я и назвал папку pseudoTests, это просто примеры использования, чтобы можно было проще понять как классами пользоваться

Тесты с докой я пишу уже в самом конце, когда функционал является завершенным

2022-01-24 06:53 UTC, DonVietnam requested changes

2022-01-24 06:53 UTC, DonVietnam commented on Practice/cbrgpl/service/responseProcessor.js
> +  constructor( mimeParserPairs, invalidStatuses = [] ) {
@cbrgpl Конкретного ответа тебе никто не даст. Проводить границы между сущностями - это навык, который нужно оттачивать какое-то время. Но тут очевидно, что этот параметр проходит через несколько конструкторов, а это значит, что для того, чтобы использовать класс ResponseProcessor, я должен знать как работает класс MimeTypeParser. Если я это и так должен знать, то можно мне самому сделать этот MimeTypeParser и передать его, как готовый объект в ResponseProcessor, таким образом мы хотя бы уберём лишнюю ответственность за создание вспомогательного класса у ResponseProcessor.

2022-01-24 06:53 UTC, DonVietnam commented on Practice/cbrgpl/service/serviceFactory.js
> +    if( !( serviceFactory instanceof ServiceFactory ) && serviceFactory.prototype !== ServiceFactory ) {
Если кто-то наследуется через prototype, то наша задача - дать ему по рукам и отучить. Не стоит из-за этого городить чудо проверки прототипов. Прототипы - прошлое.

2022-01-24 06:53 UTC, DonVietnam commented on Practice/cbrgpl/service/serviceFactory.js
> +  }
Если ты хочешь, чтобы была возможность делать "обёртки" вокруг твоего сервиса, то пусть используют наследование(extends), которое для этого нужно и просто в super() передают нужные параметры. Фабрики должны иметь общий интерфейс, но могут иметь разную реализацию, это и есть полиморфизм.
То есть суть в том, что твоя фабрика приходит в клиентский код, клиентскому коду всё ровно какая это фабрика, он просто вызывает у неё метод create.
```
const { ResponseProcessor } = require( './../service/responseProcessor' );
const mimeParserPairs = {
  'application/json': ( val ) => {
    console.log( 'mimeParser', val );
    return val;
  }
};
getServicesForApi( ServiceFactory, api ) {
  const responseProcessor = new ResponseProcessor( mimeParserPairs );
/*Хотя создание фабрики лучше вынести в вызывающую функцию, потому что это не совсем естественно - передавать класс, но раз у на JS, то, наверное, нет смысла отказываться от такого.*/
  const serviceFactory = new ServiceFactory( { responseProcessor } );// Без разницы, какая это фабрика.
  const services = serviceFactory .generateServices( api ); //У них у всех одинаковый интерфейс. 
  console.log( services );
}
```

2022-01-24 06:53 UTC, DonVietnam commented on Practice/cbrgpl/service/serviceFactory.js
> +  static generateServices( serviceFactory, apiModules ) {
Опять таки странная реализация, я ниже пример написал, как это должно работать в нормальном ООП стиле.

2022-01-24 06:53 UTC, DonVietnam commented on Practice/cbrgpl/service/service.js
> +const { ResponseProcessor } = require( './responseProcessor' );
Зачем?

2022-01-24 06:53 UTC, DonVietnam commented on Practice/cbrgpl/service/service.js
> +      this.hooks.responseHandled( handledResponse );
На сколько я вижу, в этом классе нет такого атрибута.

2022-01-24 06:53 UTC, DonVietnam commented on Practice/cbrgpl/service/mimeTypeParser.js
> +      return this.mimeParserPairs[ responseMimeType ];
Если у тебя такая логика обработки, то мне кажется лучше воспользоваться объектом Map() и его методами has(), get() set();

2022-01-24 07:54 UTC, cbrgpl commented on Practice/cbrgpl/service/serviceFactory.js
> +    if( !( serviceFactory instanceof ServiceFactory ) && serviceFactory.prototype !== ServiceFactory ) {
@DonVietnam  А как мне тут проверять, что передаваемая factory является либо экземпляром класса ServiceFactory, либо экземпляром класса, который наследуется от ServiceFactory?

2022-01-24 08:14 UTC, cbrgpl commented on Practice/cbrgpl/service/serviceFactory.js
> +    if( !( serviceFactory instanceof ServiceFactory ) && serviceFactory.prototype !== ServiceFactory ) {
Я уже прочитал ниже, что передавать саму фабрику уже никуда не надо будет после рефакторинга, но вообще интересно все же как правильно тогда проверять, что какой-то класс является наследником другого класса, то что ты пишешь про прототипы я совсем не понял, это ведь фундаментальный принцип работы ЖСа, и тут я ничего уже не могу поделать

Как вариант можно проверять serviceFactory.constructor.name, но чем это лучше я не знаю, это ведь наоборот менее удобно

2022-01-24 12:23 UTC, cbrgpl commented
ереименовал apiEndpoint к requestParams; произвел ренейминг отдельных переменных; Создал hookClass - обертку над map, который позволяет добавлять и вызывать хуки; поправил serviceFactory в соответствие с фабричным методом. Убрал использование объектов для хуков отдельного реквеста

2022-01-25 07:41 UTC, cbrgpl commented
@DonVietnam

2022-01-25 10:03 UTC, DonVietnam requested changes
Уже появились хорошие классы, которые читаются и выглядят достаточно неплохо. Но нужно ещё немного пораспутывать этот клубок.

2022-01-25 10:03 UTC, DonVietnam commented on Practice/cbrgpl/service/serviceFactory.js
> +      apiModuleSchema,
Это параметр в конструкторе класса Service нужен только для того, чтобы создать объект класса Fetcher, догадываешься к чему я клоню? Как я уже написал пахнет фабрикой для Fetcher и вынести его создание в эту функцию, а класс Service будет его просто принимать.
p.s. когда я говорю фабрика - я имею ввиду не шаблон Фабричный метод. Фабрика может быть, как методом, так и классом. Самая простая фабрика - конструктор, но как только он становится сложнее, чем просто присвоение значений - нужно сделать фабрику. Фабрика метод - это просто метод класс, например "init", который построит этот класс, фабрика класс - я думаю понятно, отдельный класс, который по методу create возвращает объекты.

2022-01-25 10:18 UTC, cbrgpl commented on Practice/cbrgpl/service/service.js
> +  onBeforeFetch( callback ) {
beforeRequest позволяет произвести манипуляции с данными, которые будут отправляться, а beforeFetch уже с самими параметрами заголовка.

Это можно было бы все в одном хуке сделать, но я решил для наглядности разделить(пока печатал понял, что в случае если данные будут использоваться как `queryParams`, то такое разделение поможет очень удобно подготовить их к вставке), чтобы один хук работал непосредственно с данными, а другой уже с самими параметрами запроса. Возможно стоит просто переименовать, чтобы понятнее было, но я не знаю как, в документации все равно будет описан смысл каждого хука

Примером для GET запроса может быть такой сценарий
в beforeRequest мы просто делаем перевод от `camelCase` к `kebab`
в fetchRequest  в `Headers` ставим `Authorize: 'Token authentification_token_1'`

2022-01-25 11:21 UTC, cbrgpl commented on Practice/cbrgpl/service/apiModule.js
> +};
@DonVietnam  Ааа, я кажется понял. Это же по идеи паттерн `Посредник`? Если это так, то я заметил закономерность, что для класса использующего этот паттерн нужно создавать вспомогательный класс-фабрику(или функцию, но пока получаются классы), который предоставит удобный интерфейс для создания самого класса, верно?

2022-01-25 12:42 UTC, cbrgpl commented
@DonVietnam  Создал FetcherFactory; Избавился от apiModule class в пользу Map; Произвел небольшие переименования(path -> url, HookClass -> Hookable); Вынес ответственность за создание Fetcher из Service;

2022-01-25 12:50 UTC, cbrgpl commented
Что касательно деструктуризации в service.request && fetcher.request, то там специально так сделано, т.к. оба параметра(`data`, `id`) являются необязательными, т.е. возможны такие случаи:
1. !data, !id
2. !data, id
3. data, !id

Из-за этого без деструктуризации пришлось писать бы что-то вроде этого:
request(name, null, id) - в случае порядка аргументов name, data, id
request(name, null, data) - в случае порядка аргументов name id data

2022-01-25 15:16 UTC, DonVietnam requested changes

2022-01-25 15:16 UTC, DonVietnam commented on Practice/cbrgpl/service/hookable.js
> +  }
Учитывая, что она вызывается только пару раз, для того чтобы сделать определённый константный список хуков, лучше от неё избавиться, а те списки просто ручками прописать. Статические методы - не очень хорошая практика, ибо они по факту не являются членами класса.

2022-02-06 08:13 UTC, closed without merging