Accelerator Api Code Review
DonVietnam/mentoring pull request #5
Opened 2022-01-14 14:12 UTC by MChuduk

2022-01-17 12:53 UTC, DonVietnam requested changes
Смотреть тут, конечно, пока особо нечего, но уже есть что поправить, хотя в целом архитектура Nest даёт свои хорошие плоды. Единственное пока не увидел логгера адекватного и я так понимаю авторизации у тебя тут никакой нет.

2022-01-17 12:53 UTC, DonVietnam commented on Practice/liveschneider/src/events/events.service.ts
> +      calendarId: process.env.CALENDAR_ID,
Напоминаю, что ты зачем-то используешь ConfigModule...

2022-01-17 12:53 UTC, DonVietnam commented on Practice/liveschneider/src/events/events.service.ts
> +  async search(startDate: Date, endDate: Date) {
По моему скромному мнению эта функция ничего не ищет, а получает. Я уж думал, что буду сейчас алгоритм поиска ревьювить...

2022-01-17 12:53 UTC, DonVietnam commented on Practice/liveschneider/src/events/events.service.ts
> +    if (!attendees) return undefined;
Именно тут значит решил сделать валидацию входного параметра, что уже неплохо, однако возвращать undefuned идея не очень. Лучше верни пустое валидное значение для результата этой функции, у тебя это пустой массив.

2022-01-17 12:53 UTC, DonVietnam commented on Practice/liveschneider/src/events/events.service.ts
> +        attendees: await this.parseAttendees(event.attendees),
Вот этим самым await ты превратил это цикл в нечто "полусинхронное", потому что он будет ждать выполнения каждой итерации, вместо того, чтобы одновременно выполнять все запросы в gravatar. Если это устраивает в плане производительности, то всё нормально, иначе - нужно придумывать очередь промисов и ждать её через Promise.allSettled.

2022-01-17 12:53 UTC, DonVietnam commented on Practice/liveschneider/src/gravatar/gravatar.service.ts
> +  getProfilePhoto(email: string): string {
Photo или всё-таки url?

2022-01-17 12:53 UTC, DonVietnam commented on Practice/liveschneider/src/gravatar/gravatar.service.ts
> +      .catch((error) => console.log(`gravatar profile not found ${email}`));
Логировать в консоль не стоит. Я бы сказал, что и ошибки нужно в одном месте обрабатывать, но у тебя сейчас так сделано, что если ты её тут не отловишь, то загрузка всех участников события прервётся на пол пути, и если ты готов потерять один профиль и продолжить, то в данном случае это правильно. Но логи в консоль - недопустимы.

2022-04-06 14:41 UTC, MChuduk commented on liveschneider/src/workers/national-archives.worker.js
> +      return bookTickets(day, tickets, startTime, endTime);
Тут параметры не совпадают. Этот баг уже пофиксил

2022-04-07 10:48 UTC, DonVietnam approved these changes

2022-04-07 10:48 UTC, DonVietnam commented on liveschneider/src/services/worker.service.js
> +  }
Я бы не смешивал async await стили с методами промисов, всё всегда можно переписать на async await, читается и воспринимается такой код легче.

2022-04-07 10:48 UTC, DonVietnam commented on liveschneider/src/services/worker.service.js
> +  }
Дублирование логики в этих функциях. У тебя currentDay два разы через конструктор Date прогоняется.

2022-04-07 10:48 UTC, DonVietnam commented on liveschneider/src/services/worker.service.js
> +    // TODO: add second condition
Я бы нашёл для таких комментариев более подходящее место, нежели код, в котором ты про них скорее всего забудешь.

2022-04-07 10:48 UTC, DonVietnam commented on liveschneider/src/services/worker.service.js
> +        const tickets = await this.getTicketsToBooking(job, day, account);
Я думал это прям билеты, а это число :(

2022-04-07 10:48 UTC, DonVietnam commented on liveschneider/src/services/worker.service.js
> +        }
Может это исключительный случай, но важно ли ждать отправление логов и отчётов?

2022-04-07 10:48 UTC, DonVietnam commented on liveschneider/src/services/worker.service.js
> +        await this.setJobStatus(job, 'failed');
Мне кажется, что не обязательно ждать вывода логов, для того чтобы поменять статус.

2022-04-07 10:48 UTC, DonVietnam commented on liveschneider/src/services/logger.service.js
> +    console.log(message);
Надеюсь, что это только для разработки тут осталось.

2022-04-07 10:48 UTC, DonVietnam commented on liveschneider/src/services/utils.service.js
> +module.exports = new UtilsService();
У NodeJS уже достаточно собственных средств для того, чтобы хэшировать строку. Поэтому я бы не стал тащить для этого в проект лишнюю зависимость.

2022-04-07 10:48 UTC, DonVietnam commented on liveschneider/src/services/auth.service.js
> +    if (user && passwordEquals) {
Не знаю, важна ли в этом проекте авторизация, но я бы всё же делал условие строже и аккуратнее.

2022-04-07 10:48 UTC, DonVietnam commented on liveschneider/src/workers/national-archives.worker.js
> +require('dotenv').config({ path: `.${process.env.NODE_ENV}.env` });
Тут особо не хочется что-то отмечать, потому что такие файлы и функции пишутся один раз под каждый конкретный сайт. Но если что-то и отметить, так это повсеместные магические константы, которые можно было бы вынести в отдельное место в файле. Но опять же исходя из специфики и назначения этого скрипта, тут можно не особо стараться.

2022-04-07 10:48 UTC, DonVietnam commented on liveschneider/src/services/accounts.service.js
> +    return availableAccounts;
На сколько я заметил, вот эта функция вызывается только в getAvailableAccount() у worker.service и там ей нужно получить лишь один аккаунт, а не массив. Я бы в таком случае немного переделал её, так чтобы она возвращала сразу же первый подходящий аккаунт, а в дальнейшем, если понадобиться, переделал бы обратно.

2022-04-11 13:57 UTC, closed without merging