Использовал паттерн Команда для реализации запроса данных, состоящего…
DonVietnam/mentoring pull request #7
Opened 2022-02-06 08:32 UTC by cbrgpl

… из нескольки реквестов по разным ручка

Создал пример команды для запроса основных данных пользователя и билетов(например в кинотеатр), которые относятся к его аккаунту

2022-02-06 13:09 UTC, cbrgpl commented
Upd 1 - решил не экспортировать конструктор, а сразу экспортировать готовые команды, потому что никаких динамических параметров в конструктор не передается

2022-02-17 05:29 UTC, DonVietnam requested changes
Проверил, и я не совсем понял зачем вся эта реализация, выглядит просто как очередная усложненная абстракция...
Какую проблему ты решил шаблоном "Команда". Этот шаблон - вид стратегии, значит команды должны иметь одинаковый интерфейс, но разную реализацию, тут же я вижу, что интефейс одинаковый только касательно метода execute, а конструктор у них разный. Но это так, пока что главный вопрос - зачем и что решаешь этими вот абстракциями?

2022-02-17 05:29 UTC, DonVietnam commented on Practice/cbrgpl/base_commands/serviceCommand.js
> +  }
Эта функция просто складывает какие-то непонятные обёртки промисов в очередь промисов, она не дожидается их выполнения и промисы в этой очереди вполне себе могут не иметь статуса fulfilled.

2022-02-17 05:29 UTC, DonVietnam commented on Practice/cbrgpl/base_commands/serviceCommand.js
> +    const promiseResults = await Promise.allSettled( this.promisesQueue )
А вот эта строчка, в отличии от функции fulfilRequests, ожидает выполнения всех промисов, но при этом гарантии, что среди них не будет rejected промиса тут нет

2022-02-17 05:29 UTC, DonVietnam commented on Practice/cbrgpl/base_commands/serviceCommand.js
> +    }
Ну вот как-то криво ты собираешься запросы обрабатывать, это похоже на транзакцию типа "Если один из запросов не выполнен, то не выполнились все - вернуть ошибку." Но на клиенте так не работает, если один из запросов выполнился, то он выполнился и ты его таким образом потерял. Сервер то о твоих махинациях не знает и запросы он выполняет. Тут механизм выбрасывания ошибки не подойдёт, нужно ошибки возвращать вместе с результатом.

2022-02-17 05:56 UTC, cbrgpl commented
@DonVietnam в разных местах приложения приходится использовать одинаковые цепочки запросов характеризующихся GET методом. Во избежание дублирования кода используется команда. 

Почему сделана транзакция именно в таком типе - т.к. если один запрос не выполнен, значит проблема с сервером, а не клиентом и все запросы надо обозначить не выполнены, т.к. логически они обозначают одно действие

Каждая базовая команда по сути независимый класс и единственное что связывает его с другим - паттерн. 

Ну а как я понял, считается допустимым передавать в конструктор команды необходимые для нее значения

2022-02-17 06:29 UTC, DonVietnam commented
@cbrgpl Ошибка с сервера может вернуться касательно одного запроса, а все остальные могут быть выполнены корректно и результаты этих запросов ты потеряешь или, что хуже, попробуешь эти запросы заного отправить и получишь ещё ошибки, связанные с тем с дублированием данных, например, и в этом случае опять не выполнится твоя "транзакция'. Называть это транзакцией нельзя, так как в случае не успеха, все результаты транзакции должны откатываться, ты этого сделать не в состоянии на клиенте, поэтому и реализация должны быть другой.

2022-04-11 13:57 UTC, closed without merging