warranty
DonVietnam/mentoring pull request #8
Opened 2022-02-21 20:04 UTC by alex01-kulnis

warranty

2022-02-21 20:04 UTC, alex01-kulnis commented
warranty

2022-02-27 10:30 UTC, DonVietnam requested changes

2022-02-27 10:30 UTC, DonVietnam commented on Practice/kulnis/file.txt
> +  }
Я бы не стал называть функцию существительным. По названию не очень понятно, что она делает, предположу, что переводит дату в нужный формат.

2022-02-27 10:30 UTC, DonVietnam commented on Practice/kulnis/file.txt
> +        warranty[key] != warrantyIncomingUpdate[key] &&
Я бы использовал строгое равенство, чтобы избежать приведения типов.

2022-02-27 10:30 UTC, DonVietnam commented on Practice/kulnis/file.txt
> +        +this.validFormat(warranty[key]) !=
Я бы назвал функцию dateToMs, чтобы отразить перевод даты к миллисекундам, а не оставлять это здесь. Хорошо если человек понимает это неявное преобразование, а что если нет - код становится нечитаемым.

2022-02-27 10:30 UTC, DonVietnam commented on Practice/kulnis/file.txt
> +        result.push(key);
Я бы пересмотрел условия в этом цикле, как минимум тут есть дублирующие условие.

2022-03-17 14:22 UTC, closed without merging